### ISSUE TITLE
Supporting this plugin on Windows.

### ISSUE THREAD

**Issue by TrailHacker** [jobedom/OpenFolderInVSCode#5]
I forked this repo to integrate my (local) fix to support this plugin on Windows. After forking the repository, I see it has already been fixed and [merged to master](#2). However, when installing the plugin from `fman` I'm still getting the version in [v1.1](https://github.com/jobedom/OpenFolderInVSCode/releases/tag/v1.1) release. Does it require a new release to get this to work on Windows? 

Thanks for the great plugin! :)

**Comment by jobedom** [comment]
Try now.

**Comment by TrailHacker** [comment]
Works great! Thanks!
